server:
  port: 8090
  shutdown: graceful
  error:
    include-message: always

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:postgres://localhost:5436/fake-payment-provider
    username: payment-provider
    password: payment-provider
    properties:
      schema: payment-provider
  flyway:
    enabled: on
    url: jdbc:postgresql://localhost:5436/fake-payment-provider
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    default-schema: ${spring.r2dbc.properties.schema}
    locations: classpath:db/migration
  docker:
    compose:
      enabled: false

service:
  source:
    webhook:
      transaction:
        host: http://localhost:8090/api/v1/webhook/transaction
      payout:
        host: http://localhost:8090/api/v1/webhook/payout

webClient:
  readWriteTimeoutMs: 20000

scheduling:
  enabled: true